# Generated by Django 5.0.13 on 2025-04-04 18:13

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(db_column='ROWID', primary_key=True, serialize=False)),
                ('country', models.CharField(db_column='CRY_0', default='', max_length=3, unique=True)),
                ('language', models.CharField(db_column='LAN_0', default='', max_length=3)),
                ('currency', models.CharField(db_column='CUR_0', default='', max_length=3)),
                ('create_user', models.CharField(db_column='CREUSR_0', default='INTER', max_length=5)),
                ('create_date', models.DateTimeField(db_column='CREDAT_0', default=django.utils.timezone.now)),
                ('update_user', models.CharField(db_column='UPDUSR_0', default='INTER', max_length=5)),
                ('update_date', models.DateTimeField(db_column='UPDDAT_0', default=django.utils.timezone.now)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_column='CREDATTIM_0')),
                ('update_datetime', models.DateTimeField(auto_now=True, db_column='UPDDATTIM_0')),
                ('auuid', models.BinaryField(db_column='AUUID_0', max_length='max')),
                ('updtick_0', models.IntegerField(db_column='UPDTICK_0')),
                ('eeccod_0', models.CharField(db_column='EECCOD_0', default='', max_length=3)),
                ('cinsee_0', models.CharField(db_column='CINSEE_0', default='', max_length=5)),
                ('iso_0', models.CharField(db_column='ISO_0', default='', max_length=2)),
                ('isoa3_0', models.CharField(db_column='ISOA3_0', default='', max_length=3)),
                ('isonum_0', models.CharField(db_column='ISONUM_0', default='', max_length=3)),
                ('eecflg_0', models.SmallIntegerField(db_column='EECFLG_0', default=0)),
                ('eecdat_0', models.DateTimeField(db_column='EECDAT_0', default=0)),
                ('eecdatout_0', models.DateTimeField(db_column='EECDATOUT_0', default=datetime.date(1753, 1, 1))),
                ('ctlprg_0', models.CharField(db_column='CTLPRG_0', default='', max_length=30)),
                ('naffmt_0', models.CharField(db_column='NAFFMT_0', default='', max_length=30)),
                ('telfmt_0', models.CharField(db_column='TELFMT_0', default='', max_length=30)),
                ('poscodfmt_0', models.CharField(db_column='POSCODFMT_0', default='', max_length=30)),
                ('poscodcry_0', models.CharField(db_column='POSCODCRY_0', default='', max_length=30)),
                ('ctycodfmt_0', models.CharField(db_column='CTYCODFMT_0', default='', max_length=30)),
                ('ctyupp_0', models.SmallIntegerField(db_column='CTYUPP_0', default=0)),
                ('ctynumfmt_0', models.CharField(db_column='CTYNUMFMT_0', default='', max_length=30)),
                ('adrcodfmt_0', models.CharField(db_column='ADRCODFMT_0', default='', max_length=30)),
                ('minzip_0', models.SmallIntegerField(db_column='MINZIP_0', default=0)),
                ('adrnam_0', models.CharField(db_column='ADRNAM_0', default='', max_length=20)),
                ('adrnam_1', models.CharField(db_column='ADRNAM_1', default='', max_length=20)),
                ('adrnam_2', models.CharField(db_column='ADRNAM_2', default='', max_length=20)),
                ('bidfmt_0', models.CharField(db_column='BIDFMT_0', default='', max_length=30)),
                ('pabfmt_0', models.CharField(db_column='PABFMT_0', default='', max_length=30)),
                ('bidcry_0', models.CharField(db_column='BIDCRY_0', default='', max_length=30)),
                ('crnfmt_0', models.CharField(db_column='CRNFMT_0', default='', max_length=30)),
                ('crtfmt_0', models.CharField(db_column='CRTFMT_0', default='', max_length=30)),
                ('nidfmt_0', models.CharField(db_column='NIDFMT_0', default='', max_length=30)),
                ('eecfmt_0', models.CharField(db_column='EECFMT_0', default='', max_length=30)),
                ('crnfmtflg_0', models.SmallIntegerField(db_column='CRNFMTFLG_0', default=0)),
                ('crtfmtflg_0', models.SmallIntegerField(db_column='CRTFMTFLG_0', default=0)),
                ('nidfmtflg_0', models.SmallIntegerField(db_column='NIDFMTFLG_0', default=0)),
                ('eecfmtflg_0', models.SmallIntegerField(db_column='EECFMTFLG_0', default=0)),
                ('naffmtflg_0', models.SmallIntegerField(db_column='NAFFMTFLG_0', default=0)),
                ('subdivfmt_0', models.CharField(db_column='SUBDIVFMT_0', default='', max_length=30)),
                ('cryvatnum_0', models.CharField(db_column='CRYVATNUM_0', default='', max_length=3)),
                ('continent_0', models.CharField(db_column='CONTINENT_0', default='', max_length=20)),
                ('etat_0', models.SmallIntegerField(db_column='ETAT_0', default=0)),
                ('etatflg_0', models.SmallIntegerField(db_column='ETATFLG_0', default=0)),
                ('etatflg2_0', models.SmallIntegerField(db_column='ETATFLG2_0', default=0)),
                ('etatfmt_0', models.CharField(db_column='ETATFMT_0', default='', max_length=30)),
                ('etatfmt2_0', models.CharField(db_column='ETATFMT2_0', default='', max_length=30)),
                ('etatctl_0', models.SmallIntegerField(db_column='ETATCTL_0', default=0)),
                ('socnumflg1_0', models.SmallIntegerField(db_column='SOCNUMFLG1_0', default=0)),
                ('poscodctl_0', models.SmallIntegerField(db_column='POSCODCTL_0', default=0)),
                ('bidctl_0', models.SmallIntegerField(db_column='BIDCTL_0', default=0)),
                ('banlng_0', models.SmallIntegerField(db_column='BANLNG_0', default=0)),
                ('fliban_0', models.SmallIntegerField(db_column='FLIBAN_0', default=0)),
                ('posobl_0', models.SmallIntegerField(db_column='POSOBL_0', default=0)),
                ('socnumfmt_0', models.CharField(db_column='SOCNUMFMT_0', default='', max_length=1)),
                ('crnobl_0', models.SmallIntegerField(db_column='CRNOBL_0', default=0)),
                ('crtobl_0', models.SmallIntegerField(db_column='CRTOBL_0', default=0)),
                ('teltcy_0', models.CharField(db_column='TELTCY_0', default='', max_length=10)),
                ('telreg_0', models.CharField(db_column='TELREG_0', default='', max_length=10)),
                ('flgsepa_0', models.SmallIntegerField(db_column='FLGSEPA_0', default=0)),
                ('socnumflg2_0', models.SmallIntegerField(db_column='SOCNUMFLG2_0', default=0)),
                ('bidcls_0', models.CharField(db_column='BIDCLS_0', default='', max_length=12)),
                ('socnumfmt2_0', models.CharField(db_column='SOCNUMFMT2_0', default='', max_length=1)),
                ('flgdue_0', models.SmallIntegerField(db_column='FLGDUE_0', default=0)),
                ('gspflg_0', models.SmallIntegerField(db_column='GSPFLG_0', default=0)),
                ('eoriflg_0', models.SmallIntegerField(db_column='EORIFLG_0', default=0)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'TABCOUNTRY',
                'managed': False,
            },
        ),
    ]
