# Generated by Django 5.0.13 on 2025-04-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
