from django.conf import settings
from django.db import models
from django.utils import timezone


class Customer(models.Model):
    id = models.BigAutoField(db_column='ROWID', primary_key=True)
    customer = models.CharField(db_column='BPCNUM_0', max_length=15, default='')
    company_name = models.CharField(db_column='BPCNAM_0', max_length=35, default='')
    short_description = models.CharField(db_column='BPCSHO_0', max_length=10, default='')
    category = models.CharField(db_column='BCGCOD_0', max_length=5, default='')
    group = models.CharField(db_column='GRP_0', max_length=5, default='')
    type = models.SmallIntegerField(db_column='BPCTYP_0', default=1)
    bill_to_customer = models.CharField(db_column='BPCINV_0', max_length=15, default='')
    bill_address = models.CharField(db_column='BPAINV_0', max_length=5, default='')
    pay_by_customer = models.CharField(db_column='BPCPYR_0', max_length=15, default='')
    pay_address = models.CharField(db_column='BPAPYR_0', max_length=5, default='')
    customer_group = models.CharField(db_column='BPCGRU_0', max_length=15, default='')
    risk_customer = models.CharField(db_column='BPCRSK_0', max_length=15, default='')
    default_address = models.CharField(db_column='BPAADD_0', max_length=5, default='')
    ship_to_customer_address = models.CharField(db_column='BPDADD_0', max_length=5, default='')
    default_contact = models.CharField(db_column='CNTNAM_0', max_length=35, default='')
    is_active = models.SmallIntegerField(db_column='BPCSTA_0', default=2)
    prospect = models.SmallIntegerField(db_column='PPTFLG_0', default=1)
    supplier_number = models.CharField(db_column='BPCBPSNUM_0', max_length=15, default='')
    factor = models.CharField(db_column='FCTNUM_0', max_length=15, default='')
    currency = models.CharField(db_column='CUR_0', max_length=3, default='')
    rate_type = models.SmallIntegerField(db_column='CHGTYP_0', default=1)
    commission_category = models.SmallIntegerField(db_column='COMCAT_0', default=1)
    sales_rep_0 = models.CharField(db_column='REP_0', max_length=15, default='')
    sales_rep_1 = models.CharField(db_column='REP_1', max_length=15, default='')
    tax_rule = models.CharField(db_column='VACBPR_0', max_length=5, default='')
    exemption_number = models.CharField(db_column='VATEXN_0', max_length=15, default='')
    payment_term = models.CharField(db_column='PTE_0', max_length=15, default='')
    freight_invoicing = models.SmallIntegerField(db_column='FREINV_0', default=1)
    settlement_discount = models.CharField(db_column='DEP_0', max_length=5, default='')
    invoice_amount_0 = models.DecimalField(db_column='INVDTAAMT_0', max_digits=20, decimal_places=5, default=0)
    invoice_amount_1 = models.DecimalField(db_column='INVDTAAMT_1', max_digits=20, decimal_places=5, default=0)
    invoice_amount_2 = models.DecimalField(db_column='INVDTAAMT_2', max_digits=20, decimal_places=5, default=0)
    invoice_amount_3 = models.DecimalField(db_column='INVDTAAMT_3', max_digits=20, decimal_places=5, default=0)
    invoice_amount_4 = models.DecimalField(db_column='INVDTAAMT_4', max_digits=20, decimal_places=5, default=0)
    invoice_amount_5 = models.DecimalField(db_column='INVDTAAMT_5', max_digits=20, decimal_places=5, default=0)
    invoice_amount_6 = models.DecimalField(db_column='INVDTAAMT_6', max_digits=20, decimal_places=5, default=0)
    invoice_amount_7 = models.DecimalField(db_column='INVDTAAMT_7', max_digits=20, decimal_places=5, default=0)
    invoice_amount_8 = models.DecimalField(db_column='INVDTAAMT_8', max_digits=20, decimal_places=5, default=0)
    invoice_amount_9 = models.DecimalField(db_column='INVDTAAMT_9', max_digits=20, decimal_places=5, default=0)
    invoice_amount_10 = models.DecimalField(db_column='INVDTAAMT_10', max_digits=20, decimal_places=5, default=0)
    invoice_amount_11 = models.DecimalField(db_column='INVDTAAMT_11', max_digits=20, decimal_places=5, default=0)
    invoice_amount_12 = models.DecimalField(db_column='INVDTAAMT_12', max_digits=20, decimal_places=5, default=0)
    invoice_amount_13 = models.DecimalField(db_column='INVDTAAMT_13', max_digits=20, decimal_places=5, default=0)
    invoice_amount_14 = models.DecimalField(db_column='INVDTAAMT_14', max_digits=20, decimal_places=5, default=0)
    invoice_amount_15 = models.DecimalField(db_column='INVDTAAMT_15', max_digits=20, decimal_places=5, default=0)
    invoice_amount_16 = models.DecimalField(db_column='INVDTAAMT_16', max_digits=20, decimal_places=5, default=0)
    invoice_amount_17 = models.DecimalField(db_column='INVDTAAMT_17', max_digits=20, decimal_places=5, default=0)
    invoice_amount_18 = models.DecimalField(db_column='INVDTAAMT_18', max_digits=20, decimal_places=5, default=0)
    invoice_amount_19 = models.DecimalField(db_column='INVDTAAMT_19', max_digits=20, decimal_places=5, default=0)
    invoice_amount_20 = models.DecimalField(db_column='INVDTAAMT_20', max_digits=20, decimal_places=5, default=0)
    invoice_amount_21 = models.DecimalField(db_column='INVDTAAMT_21', max_digits=20, decimal_places=5, default=0)
    invoice_amount_22 = models.DecimalField(db_column='INVDTAAMT_22', max_digits=20, decimal_places=5, default=0)
    invoice_amount_23 = models.DecimalField(db_column='INVDTAAMT_23', max_digits=20, decimal_places=5, default=0)
    invoice_amount_24 = models.DecimalField(db_column='INVDTAAMT_24', max_digits=20, decimal_places=5, default=0)
    invoice_amount_25 = models.DecimalField(db_column='INVDTAAMT_25', max_digits=20, decimal_places=5, default=0)
    invoice_amount_26 = models.DecimalField(db_column='INVDTAAMT_26', max_digits=20, decimal_places=5, default=0)
    invoice_amount_27 = models.DecimalField(db_column='INVDTAAMT_27', max_digits=20, decimal_places=5, default=0)
    invoice_amount_28 = models.DecimalField(db_column='INVDTAAMT_28', max_digits=20, decimal_places=5, default=0)
    invoice_amount_29 = models.DecimalField(db_column='INVDTAAMT_29', max_digits=20, decimal_places=5, default=0)
    invoicing_element_0 = models.SmallIntegerField(db_column='INVDTA_0', default=0)
    invoicing_element_1 = models.SmallIntegerField(db_column='INVDTA_1', default=0)
    invoicing_element_2 = models.SmallIntegerField(db_column='INVDTA_2', default=0)
    invoicing_element_3 = models.SmallIntegerField(db_column='INVDTA_3', default=0)
    invoicing_element_4 = models.SmallIntegerField(db_column='INVDTA_4', default=0)
    invoicing_element_5 = models.SmallIntegerField(db_column='INVDTA_5', default=0)
    invoicing_element_6 = models.SmallIntegerField(db_column='INVDTA_6', default=0)
    invoicing_element_7 = models.SmallIntegerField(db_column='INVDTA_7', default=0)
    invoicing_element_8 = models.SmallIntegerField(db_column='INVDTA_8', default=0)
    invoicing_element_9 = models.SmallIntegerField(db_column='INVDTA_9', default=0)
    invoicing_element_10 = models.SmallIntegerField(db_column='INVDTA_10', default=0)
    invoicing_element_11 = models.SmallIntegerField(db_column='INVDTA_11', default=0)
    invoicing_element_12 = models.SmallIntegerField(db_column='INVDTA_12', default=0)
    invoicing_element_13 = models.SmallIntegerField(db_column='INVDTA_13', default=0)
    invoicing_element_14 = models.SmallIntegerField(db_column='INVDTA_14', default=0)
    invoicing_element_15 = models.SmallIntegerField(db_column='INVDTA_15', default=0)
    invoicing_element_16 = models.SmallIntegerField(db_column='INVDTA_16', default=0)
    invoicing_element_17 = models.SmallIntegerField(db_column='INVDTA_17', default=0)
    invoicing_element_18 = models.SmallIntegerField(db_column='INVDTA_18', default=0)
    invoicing_element_19 = models.SmallIntegerField(db_column='INVDTA_19', default=0)
    invoicing_element_20 = models.SmallIntegerField(db_column='INVDTA_20', default=0)
    invoicing_element_21 = models.SmallIntegerField(db_column='INVDTA_21', default=0)
    invoicing_element_22 = models.SmallIntegerField(db_column='INVDTA_22', default=0)
    invoicing_element_23 = models.SmallIntegerField(db_column='INVDTA_23', default=0)
    invoicing_element_24 = models.SmallIntegerField(db_column='INVDTA_24', default=0)
    invoicing_element_25 = models.SmallIntegerField(db_column='INVDTA_25', default=0)
    invoicing_element_26 = models.SmallIntegerField(db_column='INVDTA_26', default=0)
    invoicing_element_27 = models.SmallIntegerField(db_column='INVDTA_27', default=0)
    invoicing_element_28 = models.SmallIntegerField(db_column='INVDTA_28', default=0)
    invoicing_element_29 = models.SmallIntegerField(db_column='INVDTA_29', default=0)
    statistical_group_0 = models.CharField(db_column='TSCCOD_0', max_length=20, default='')
    statistical_group_1 = models.CharField(db_column='TSCCOD_1', max_length=20, default='')
    statistical_group_2 = models.CharField(db_column='TSCCOD_2', max_length=20, default='')
    statistical_group_3 = models.CharField(db_column='TSCCOD_3', max_length=20, default='')
    statistical_group_4 = models.CharField(db_column='TSCCOD_4', max_length=20, default='')
    price_type = models.SmallIntegerField(db_column='PRITYP_0', default=0)
    notes = models.CharField(db_column='BPCREM_0', max_length=250, default='')
    credit_control = models.SmallIntegerField(db_column='OSTCTL_0', default=0)
    authorized_credit = models.DecimalField(db_column='OSTAUZ_0', max_digits=27, decimal_places=13, default=0)
    min_order_amount = models.DecimalField(db_column='ORDMINAMT_0', max_digits=27, decimal_places=13, default=0)
    credit_insurance = models.DecimalField(db_column='CDTISR_0', max_digits=27, decimal_places=13, default=0)
    insurance_date = models.DateTimeField(db_column='CDTISRDAT_0', default=settings.DEFAULT_LEGACY_DATE)
    insurance_company = (models.CharField(db_column='BPCCDTISR_0', max_length=15, default=''),)
    reminder_type = models.SmallIntegerField(db_column='FUPTYP_0', default=0)
    minimum_reminder = models.DecimalField(db_column='FUPMINAMT_0', max_digits=27, decimal_places=13, default=0)
    note_type = models.SmallIntegerField(db_column='SOIPER_0', default=0)
    payment_bank = models.CharField(db_column='PAYBAN_0', max_length=5, default='')
    accounting_code = models.CharField(db_column='ACCCOD_0', max_length=10, default='')
    dimension_type_code_0 = models.CharField(db_column='DIE_0', max_length=3, default='')
    dimension_type_code_1 = models.CharField(db_column='DIE_1', max_length=3, default='')
    dimension_type_code_2 = models.CharField(db_column='DIE_2', max_length=3, default='')
    dimension_type_code_3 = models.CharField(db_column='DIE_3', max_length=3, default='')
    dimension_type_code_4 = models.CharField(db_column='DIE_4', max_length=3, default='')
    dimension_type_code_5 = models.CharField(db_column='DIE_5', max_length=3, default='')
    dimension_type_code_6 = models.CharField(db_column='DIE_6', max_length=3, default='')
    dimension_type_code_7 = models.CharField(db_column='DIE_7', max_length=3, default='')
    dimension_type_code_8 = models.CharField(db_column='DIE_8', max_length=3, default='')
    dimension_type_code_9 = models.CharField(db_column='DIE_9', max_length=3, default='')
    dimension_type_code_10 = models.CharField(db_column='DIE_10', max_length=3, default='')
    dimension_type_code_11 = models.CharField(db_column='DIE_11', max_length=3, default='')
    dimension_type_code_12 = models.CharField(db_column='DIE_12', max_length=3, default='')
    dimension_type_code_13 = models.CharField(db_column='DIE_13', max_length=3, default='')
    dimension_type_code_14 = models.CharField(db_column='DIE_14', max_length=3, default='')
    dimension_type_code_15 = models.CharField(db_column='DIE_15', max_length=3, default='')
    dimension_type_code_16 = models.CharField(db_column='DIE_16', max_length=3, default='')
    dimension_type_code_17 = models.CharField(db_column='DIE_17', max_length=3, default='')
    dimension_type_code_18 = models.CharField(db_column='DIE_18', max_length=3, default='')
    dimension_type_code_19 = models.CharField(db_column='DIE_19', max_length=3, default='')
    dimension_0 = models.CharField(db_column='CCE_0', max_length=15, default='')
    dimension_1 = models.CharField(db_column='CCE_1', max_length=15, default='')
    dimension_2 = models.CharField(db_column='CCE_2', max_length=15, default='')
    dimension_3 = models.CharField(db_column='CCE_3', max_length=15, default='')
    dimension_4 = models.CharField(db_column='CCE_4', max_length=15, default='')
    dimension_5 = models.CharField(db_column='CCE_5', max_length=15, default='')
    dimension_6 = models.CharField(db_column='CCE_6', max_length=15, default='')
    dimension_7 = models.CharField(db_column='CCE_7', max_length=15, default='')
    dimension_8 = models.CharField(db_column='CCE_8', max_length=15, default='')
    dimension_9 = models.CharField(db_column='CCE_9', max_length=15, default='')
    dimension_10 = models.CharField(db_column='CCE_10', max_length=15, default='')
    dimension_11 = models.CharField(db_column='CCE_11', max_length=15, default='')
    dimension_12 = models.CharField(db_column='CCE_12', max_length=15, default='')
    dimension_13 = models.CharField(db_column='CCE_13', max_length=15, default='')
    dimension_14 = models.CharField(db_column='CCE_14', max_length=15, default='')
    dimension_15 = models.CharField(db_column='CCE_15', max_length=15, default='')
    dimension_16 = models.CharField(db_column='CCE_16', max_length=15, default='')
    dimension_17 = models.CharField(db_column='CCE_17', max_length=15, default='')
    dimension_18 = models.CharField(db_column='CCE_18', max_length=15, default='')
    dimension_19 = models.CharField(db_column='CCE_19', max_length=15, default='')
    matchable = models.SmallIntegerField(db_column='MTCFLG_0', default=0)
    order_text_0 = models.CharField(db_column='ORDTEX_0', max_length=17, default='')
    invoice_text_0 = models.CharField(db_column='INVTEX_0', max_length=17, default='')
    loan_authorized = models.SmallIntegerField(db_column='LNDAUZ_0', default=0)
    print_acknowledgment = models.SmallIntegerField(db_column='OCNFLG_0', default=0)
    invoice_period = models.SmallIntegerField(db_column='INVPER_0', default=0)
    due_date_origin = models.SmallIntegerField(db_column='DUDCLC_0', default=0)
    close_unfilled_lines = models.SmallIntegerField(db_column='ORDCLE_0', default=0)
    one_order_per_delivery = models.SmallIntegerField(db_column='ODL_0', default=0)
    partial_delivery = models.SmallIntegerField(db_column='DME_0', default=0)
    invoicing_mode = models.SmallIntegerField(db_column='IME_0', default=0)
    business = models.CharField(db_column='BUS_0', max_length=20, default='')
    source = models.CharField(db_column='ORIPPT_0', max_length=20, default='')
    token_credits = models.IntegerField(db_column='PITCDT_0', default=0)
    additional_info = models.IntegerField(db_column='PITCPT_0', default=0)
    total_credit = models.IntegerField(db_column='TOTPIT_0', default=0)
    service_contract = models.CharField(db_column='COTCHX_0', max_length=20, default='')
    tokens_necessary = models.IntegerField(db_column='COTPITRQD_0', default=0)
    first_contact_date = models.DateTimeField(db_column='CNTFIRDAT_0', default=settings.DEFAULT_LEGACY_DATE)
    first_order_date = models.DateTimeField(db_column='ORDFIRDAT_0', default=settings.DEFAULT_LEGACY_DATE)
    last_quote_date = models.DateTimeField(db_column='QUOLASDAT_0', default=settings.DEFAULT_LEGACY_DATE)
    last_contact_date = models.DateTimeField(db_column='CNTLASDAT_0', default=settings.DEFAULT_LEGACY_DATE)
    next_contact_date = models.DateTimeField(db_column='CNTNEXDAT_0', default=settings.DEFAULT_LEGACY_DATE)
    last_contact_type = models.SmallIntegerField(db_column='CNTLASTYP_0', default=settings.DEFAULT_LEGACY_DATE)
    next_contact_type = models.SmallIntegerField(db_column='CNTNEXTYP_0', default=settings.DEFAULT_LEGACY_DATE)
    abc_class = models.SmallIntegerField(db_column='ABCCLS_0', default=0)
    vat_collection_agent = models.SmallIntegerField(db_column='AGTPCP_0', default=0)
    regional_taxes = models.SmallIntegerField(db_column='AGTSATTAX_0', default=0)
    provinces = models.CharField(db_column='SATTAX_0', max_length=1, default='')
    regional_collection_agent = models.SmallIntegerField(db_column='FLGSATTAX_0', default=0)
    template_code = models.CharField(db_column='TPMCOD_0', max_length=5, default='')
    account_structure = models.CharField(db_column='DIA_0', max_length=10, default='')
    customer_since = models.DateTimeField(db_column='BPCSNCDAT_0', default=settings.DEFAULT_LEGACY_DATE)
    day_of_month_0 = models.SmallIntegerField(db_column='DAYMON_0', default=0)
    day_of_month_1 = models.SmallIntegerField(db_column='DAYMON_1', default=0)
    day_of_month_2 = models.SmallIntegerField(db_column='DAYMON_2', default=0)
    day_of_month_3 = models.SmallIntegerField(db_column='DAYMON_3', default=0)
    day_of_month_4 = models.SmallIntegerField(db_column='DAYMON_4', default=0)
    day_of_month_5 = models.SmallIntegerField(db_column='DAYMON_5', default=0)
    unavailable_period = models.CharField(db_column='UVYCOD2_0', max_length=5, default='')
    tax_rule_0 = models.SmallIntegerField(db_column='CSHVATRGM_0', default=1)
    tax_rule_1 = models.SmallIntegerField(db_column='CSHVATRGM_1', default=0)
    tax_rule_2 = models.SmallIntegerField(db_column='CSHVATRGM_2', default=0)
    tax_rule_3 = models.SmallIntegerField(db_column='CSHVATRGM_3', default=0)
    tax_rule_4 = models.SmallIntegerField(db_column='CSHVATRGM_4', default=0)
    tax_rule_5 = models.SmallIntegerField(db_column='CSHVATRGM_5', default=0)
    tax_rule_6 = models.SmallIntegerField(db_column='CSHVATRGM_6', default=0)
    tax_rule_7 = models.SmallIntegerField(db_column='CSHVATRGM_7', default=0)
    tax_rule_8 = models.SmallIntegerField(db_column='CSHVATRGM_8', default=0)
    vat_start_date_0 = models.DateTimeField(db_column='VATSTRDAT_0', default=settings.DEFAULT_LEGACY_DATE)
    vat_start_date_1 = models.DateTimeField(db_column='VATSTRDAT_1', default=settings.DEFAULT_LEGACY_DATE)
    vat_start_date_2 = models.DateTimeField(db_column='VATSTRDAT_2', default=settings.DEFAULT_LEGACY_DATE)
    vat_start_date_3 = models.DateTimeField(db_column='VATSTRDAT_3', default=settings.DEFAULT_LEGACY_DATE)
    vat_start_date_4 = models.DateTimeField(db_column='VATSTRDAT_4', default=settings.DEFAULT_LEGACY_DATE)
    vat_start_date_5 = models.DateTimeField(db_column='VATSTRDAT_5', default=settings.DEFAULT_LEGACY_DATE)
    vat_start_date_6 = models.DateTimeField(db_column='VATSTRDAT_6', default=settings.DEFAULT_LEGACY_DATE)
    vat_start_date_7 = models.DateTimeField(db_column='VATSTRDAT_7', default=settings.DEFAULT_LEGACY_DATE)
    vat_start_date_8 = models.DateTimeField(db_column='VATSTRDAT_8', default=settings.DEFAULT_LEGACY_DATE)
    vat_end_date_0 = models.DateTimeField(db_column='VATENDDAT_0', default=settings.DEFAULT_LEGACY_DATE)
    vat_end_date_1 = models.DateTimeField(db_column='VATENDDAT_1', default=settings.DEFAULT_LEGACY_DATE)
    vat_end_date_2 = models.DateTimeField(db_column='VATENDDAT_2', default=settings.DEFAULT_LEGACY_DATE)
    vat_end_date_3 = models.DateTimeField(db_column='VATENDDAT_3', default=settings.DEFAULT_LEGACY_DATE)
    vat_end_date_4 = models.DateTimeField(db_column='VATENDDAT_4', default=settings.DEFAULT_LEGACY_DATE)
    vat_end_date_5 = models.DateTimeField(db_column='VATENDDAT_5', default=settings.DEFAULT_LEGACY_DATE)
    vat_end_date_6 = models.DateTimeField(db_column='VATENDDAT_6', default=settings.DEFAULT_LEGACY_DATE)
    vat_end_date_7 = models.DateTimeField(db_column='VATENDDAT_7', default=settings.DEFAULT_LEGACY_DATE)
    vat_end_date_8 = models.DateTimeField(db_column='VATENDDAT_8', default=settings.DEFAULT_LEGACY_DATE)
    is_subject_to_tax = models.SmallIntegerField(db_column='BELVATSUB_0', default=0)
    invoice_term = models.CharField(db_column='INVCND_0', max_length=20, default='')
    is_efat_invoice = models.SmallIntegerField(db_column='ELECTINV_0', default=1)
    contact = models.CharField(db_column='CNTEFAT_0', max_length=15, default='')
    start_date = models.DateTimeField(db_column='STRDATEFAT_0', default=settings.DEFAULT_LEGACY_DATE)
    is_electronic_invoice = models.SmallIntegerField(db_column='AEIFLG_0', default=1)

    export_number = models.IntegerField(db_column='EXPNUM_0', default=0)
    create_user = models.CharField(db_column='CREUSR_0', max_length=5, default='INTER')
    create_date = models.DateTimeField(db_column='CREDAT_0', default=timezone.now)
    update_user = models.CharField(db_column='UPDUSR_0', max_length=5, default='INTER')
    update_date = models.DateTimeField(db_column='UPDDAT_0', default=timezone.now)
    create_datetime = models.DateTimeField(db_column='CREDATTIM_0', auto_now_add=True)
    update_datetime = models.DateTimeField(db_column='UPDDATTIM_0', auto_now=True)

    auuid = models.BinaryField(db_column='AUUID_0')
    updtick = models.IntegerField(db_column='UPDTICK_0', default=1)

    class Meta:
        managed = False
        db_table = 'BPCUSTOMER'
        unique_together = (('company_name', 'customer'),)
        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'
