from django.db import models
from django.utils import timezone


class Partner(models.Model):
    id = models.BigAutoField(db_column='ROWID', primary_key=True)
    bp = models.CharField(db_column='BPRNUM_0', unique=True, max_length=15, default='')
    is_active = models.SmallIntegerField(db_column='ENAFLG_0', default=2)
    category = models.CharField(db_column='BRGCOD_0', max_length=5, default='')
    customer_or_supplier_origin_category = models.CharField(db_column='BRGOBJ_0', max_length=3, default='')
    company_name_0 = models.CharField(db_column='BPRNAM_0', max_length=35, default='')
    company_name_1 = models.CharField(db_column='BPRNAM_1', max_length=35, default='')
    short_description = models.CharField(db_column='BPRSHO_0', max_length=10, default='')
    european_vat_number = models.CharField(db_column='EECNUM_0', max_length=20, default='')
    is_inter_site = models.SmallIntegerField(db_column='BETFCY_0', default=1)
    site = models.CharField(db_column='FCY_0', max_length=5, default='')
    country = models.CharField(db_column='CRY_0', max_length=3, default='')
    site_identification_number = models.CharField(db_column='CRN_0', max_length=20, default='')
    standard_industrial_classification_code = models.CharField(db_column='NAF_0', max_length=1, default='')
    currency = models.CharField(db_column='CUR_0', max_length=3, default='')
    language = models.CharField(db_column='LAN_0', max_length=3, default='')
    acronym = models.CharField(db_column='BPRLOG_0', max_length=10, default='')
    italian_tax_number = models.CharField(db_column='VATNUM_0', max_length=1, default='')
    fiscal_code = models.CharField(db_column='FISCOD_0', max_length=1, default='')
    consolidation_group = models.CharField(db_column='GRUGPY_0', max_length=5, default='')
    consolidation_code = models.CharField(db_column='GRUCOD_0', max_length=1, default='')
    is_customer = models.SmallIntegerField(db_column='BPCFLG_0', default=1)
    is_supplier = models.SmallIntegerField(db_column='BPSFLG_0', default=1)
    is_grantor = models.SmallIntegerField(db_column='CCNFLG_0', default=1)
    is_carrier = models.SmallIntegerField(db_column='BPTFLG_0', default=1)
    is_factor = models.SmallIntegerField(db_column='FCTFLG_0', default=1)
    is_sales_representative = models.SmallIntegerField(db_column='REPFLG_0', default=1)
    is_miscellaneous_business_partner = models.SmallIntegerField(db_column='BPRACC_0', default=1)
    is_prospect = models.SmallIntegerField(db_column='PPTFLG_0', default=1)
    is_service_supplier = models.SmallIntegerField(db_column='PRVFLG_0', default=1)
    is_service_caller = models.SmallIntegerField(db_column='DOOFLG_0', default=1)
    accounting_code = models.CharField(db_column='ACCCOD_0', max_length=10, default='')
    ship_to = models.SmallIntegerField(db_column='PTHFLG_0', default=0)
    miscellaneous_flag_0 = models.SmallIntegerField(db_column='BPRFLG_0', default=0)
    miscellaneous_flag_1 = models.SmallIntegerField(db_column='BPRFLG_1', default=0)
    miscellaneous_flag_2 = models.SmallIntegerField(db_column='BPRFLG_2', default=0)
    miscellaneous_flag_3 = models.SmallIntegerField(db_column='BPRFLG_3', default=0)
    default_address = models.CharField(db_column='BPAADD_0', max_length=5, default='')
    default_contact = models.CharField(db_column='CNTNAM_0', max_length=35, default='')
    default_bank_id = models.CharField(db_column='BIDNUM_0', max_length=30, default='')
    country_bank_id = models.CharField(db_column='BIDCRY_0', max_length=3, default='')
    report_access_code = models.CharField(db_column='ACS_0', max_length=10, default='')
    expense_entry_type = models.CharField(db_column='BPRGTETYP_0', max_length=5, default='')
    is_mailing_prohibited = models.SmallIntegerField(db_column='BPRFBDMAG_0', default=0)
    cfonb_payment_method = models.CharField(db_column='MODPAM_0', max_length=20, default='')
    non_resident_account = models.CharField(db_column='ACCNONREI_0', max_length=5, default='')
    is_physical_person = models.SmallIntegerField(db_column='LEGETT_0', default=1)
    is_cash_excluded = models.SmallIntegerField(db_column='CFOEXD_0', default=1)
    document_type = models.SmallIntegerField(db_column='DOCTYP_0', default=1)
    is_public_sector = models.SmallIntegerField(db_column='BPPFLG_0', default=1)
    related_company = models.SmallIntegerField(db_column='CPYREL_0', default=0)
    consolidation_partner = models.CharField(db_column='CSLBPR_0', max_length=1, default='')
    registration_number = models.CharField(db_column='REGNUM_0', max_length=1, default='')
    vat_number = models.CharField(db_column='VATNO_0', max_length=1, default='')
    eori_number = models.CharField(db_column='EORINUM_0', max_length=35, default='')
    service_code = models.CharField(db_column='INTSRVCOD_0', max_length=1, default='')
    routing_code = models.CharField(db_column='RTGCOD_0', max_length=1, default='')
    electronic_invoice_type = models.SmallIntegerField(db_column='EINVTYP_0', default=0)
    e_invoicing_mapping_code = models.CharField(db_column='MAPCOD_0', max_length=1, default='')
    export_number = models.IntegerField(db_column='EXPNUM_0', default=0)
    create_user = models.CharField(db_column='CREUSR_0', max_length=5, default='INTER')
    create_date = models.DateTimeField(db_column='CREDAT_0', default=timezone.now)
    update_user = models.CharField(db_column='UPDUSR_0', max_length=5, default='INTER')
    update_date = models.DateTimeField(db_column='UPDDAT_0', default=timezone.now)
    create_datetime = models.DateTimeField(db_column='CREDATTIM_0', auto_now_add=True)
    update_datetime = models.DateTimeField(db_column='UPDDATTIM_0', auto_now=True)
    auuid = models.BinaryField(db_column='AUUID_0')
    updtick = models.IntegerField(db_column='UPDTICK_0', default=1)

    class Meta:
        managed = False
        db_table = 'BPARTNER'
        unique_together = (('is_inter_site', 'site', 'bp'),)
        verbose_name = 'Partner'
        verbose_name_plural = 'Partners'
