# Generated by Django 5.0.13 on 2025-04-02 03:08

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 5 characters or fewer. Letters and digits.', max_length=5, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z][A-Za-z0-9]*$'), 'Enter a valid username.', 'invalid')], verbose_name='username'),
        ),
    ]
