# Generated by Django 5.0.13 on 2025-04-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'managed': False, 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
    ]
