from django.conf import settings
from django.db import models
from django.utils import timezone


class Ticket(models.Model):
    id = models.BigAutoField(db_column='ROWID', primary_key=True)
    service_number = models.CharField(db_column='SRENUM_0', unique=True, max_length=20, verbose_name='Service Number')
    customer = models.CharField(db_column='SREBPC_0', max_length=15, default='', verbose_name='Customer')
    customer_invoice = models.CharField(db_column='SREBPCINV_0', max_length=15, default='')
    customer_payment = models.CharField(db_column='SREBPCPYR_0', max_length=15, default='')
    customer_group = models.CharField(db_column='SREBPCGRU_0', max_length=15, default='')
    customer_address_code = models.CharField(db_column='SREBPAADD_0', max_length=5, default='')
    relationship = models.CharField(db_column='SRECCN_0', max_length=15, default='', verbose_name='Relationship')
    currency = models.CharField(db_column='SRECUR_0', max_length=3, default='EUR')
    sales_site = models.CharField(db_column='SALFCY_0', max_length=5, default='')
    title = models.CharField(db_column='SRETTR_0', max_length=80, default='', verbose_name='Title')
    description = models.CharField(db_column='SREDES_0', max_length=250, default='')
    ticket_date = models.DateTimeField(
        db_column='SREDATASS_0', default=settings.DEFAULT_LEGACY_DATE, verbose_name='Ticket Date'
    )
    ticket_hour = models.CharField(db_column='SREHOUASS_0', max_length=6, default=timezone.now().strftime('%H:%M:%S'))
    ticket_status = models.CharField(db_column='SRESAT_0', max_length=20, default='', verbose_name='Status')
    resolution_date = models.DateTimeField(
        db_column='SRERESDAT_0', default=settings.DEFAULT_LEGACY_DATE, verbose_name='Resolution Date'
    )
    create_user = models.CharField(db_column='CREUSR_0', max_length=5, default='INTER')
    create_date = models.DateTimeField(db_column='CREDAT_0', default=timezone.now)
    create_hour = models.CharField(db_column='CREHOU_0', max_length=6, default=timezone.now().strftime('%H:%M:%S'))
    update_user = models.CharField(db_column='UPDUSR_0', max_length=5, default='INTER')
    update_date = models.DateTimeField(db_column='UPDDAT_0', default=timezone.now)
    create_datetime = models.DateTimeField(db_column='CREDATTIM_0', auto_now_add=True)
    update_datetime = models.DateTimeField(db_column='UPDDATTIM_0', auto_now=True)
    auuid_0 = models.BinaryField(db_column='AUUID_0')

    updtick = models.IntegerField(db_column='UPDTICK_0', default=1)
    srereshou_0 = models.CharField(db_column='SRERESHOU_0', max_length=6, default='')
    typfuldes_0 = models.CharField(db_column='TYPFULDES_0', max_length=10, default='')
    sreass_0 = models.SmallIntegerField(db_column='SREASS_0', default=1)
    sredet_0 = models.CharField(db_column='SREDET_0', max_length=20, default='')
    srenumbpc_0 = models.CharField(db_column='SRENUMBPC_0', max_length=20, default='')
    sreinumbpc_0 = models.IntegerField(db_column='SREINUMBPC_0', default=0)
    sredoo_0 = models.CharField(db_column='SREDOO_0', max_length=15, default='')
    srepjt_0 = models.CharField(db_column='SREPJT_0', max_length=40, default='')
    srerep_0 = models.CharField(db_column='SREREP_0', max_length=15, default='')
    srerep_1 = models.CharField(db_column='SREREP_1', max_length=15, default='')
    sremac_0 = models.CharField(db_column='SREMAC_0', max_length=20, default='')
    sremacpbl_0 = models.CharField(db_column='SREMACPBL_0', max_length=20, default='')
    stofcy_0 = models.CharField(db_column='STOFCY_0', max_length=5, default='')
    srevacbpr_0 = models.CharField(db_column='SREVACBPR_0', max_length=5, default='')
    sstentcod_0 = models.CharField(db_column='SSTENTCOD_0', max_length=10, default='')
    srechgtyp_0 = models.SmallIntegerField(db_column='SRECHGTYP_0', default=0)
    sreprityp_0 = models.SmallIntegerField(db_column='SREPRITYP_0', default=0)
    srepte_0 = models.CharField(db_column='SREPTE_0', max_length=15, default='')
    sredep_0 = models.CharField(db_column='SREDEP_0', max_length=5, default='')
    die_0 = models.CharField(db_column='DIE_0', max_length=3, default='')
    die_1 = models.CharField(db_column='DIE_1', max_length=3, default='')
    die_2 = models.CharField(db_column='DIE_2', max_length=3, default='')
    die_3 = models.CharField(db_column='DIE_3', max_length=3, default='')
    die_4 = models.CharField(db_column='DIE_4', max_length=3, default='')
    die_5 = models.CharField(db_column='DIE_5', max_length=3, default='')
    die_6 = models.CharField(db_column='DIE_6', max_length=3, default='')
    die_7 = models.CharField(db_column='DIE_7', max_length=3, default='')
    die_8 = models.CharField(db_column='DIE_8', max_length=3, default='')
    die_9 = models.CharField(db_column='DIE_9', max_length=3, default='')
    die_10 = models.CharField(db_column='DIE_10', max_length=3, default='')
    die_11 = models.CharField(db_column='DIE_11', max_length=3, default='')
    die_12 = models.CharField(db_column='DIE_12', max_length=3, default='')
    die_13 = models.CharField(db_column='DIE_13', max_length=3, default='')
    die_14 = models.CharField(db_column='DIE_14', max_length=3, default='')
    die_15 = models.CharField(db_column='DIE_15', max_length=3, default='')
    die_16 = models.CharField(db_column='DIE_16', max_length=3, default='')
    die_17 = models.CharField(db_column='DIE_17', max_length=3, default='')
    die_18 = models.CharField(db_column='DIE_18', max_length=3, default='')
    die_19 = models.CharField(db_column='DIE_19', max_length=3, default='')
    cce_0 = models.CharField(db_column='CCE_0', max_length=15, default='')
    cce_1 = models.CharField(db_column='CCE_1', max_length=15, default='')
    cce_2 = models.CharField(db_column='CCE_2', max_length=15, default='')
    cce_3 = models.CharField(db_column='CCE_3', max_length=15, default='')
    cce_4 = models.CharField(db_column='CCE_4', max_length=15, default='')
    cce_5 = models.CharField(db_column='CCE_5', max_length=15, default='')
    cce_6 = models.CharField(db_column='CCE_6', max_length=15, default='')
    cce_7 = models.CharField(db_column='CCE_7', max_length=15, default='')
    cce_8 = models.CharField(db_column='CCE_8', max_length=15, default='')
    cce_9 = models.CharField(db_column='CCE_9', max_length=15, default='')
    cce_10 = models.CharField(db_column='CCE_10', max_length=15, default='')
    cce_11 = models.CharField(db_column='CCE_11', max_length=15, default='')
    cce_12 = models.CharField(db_column='CCE_12', max_length=15, default='')
    cce_13 = models.CharField(db_column='CCE_13', max_length=15, default='')
    cce_14 = models.CharField(db_column='CCE_14', max_length=15, default='')
    cce_15 = models.CharField(db_column='CCE_15', max_length=15, default='')
    cce_16 = models.CharField(db_column='CCE_16', max_length=15, default='')
    cce_17 = models.CharField(db_column='CCE_17', max_length=15, default='')
    cce_18 = models.CharField(db_column='CCE_18', max_length=15, default='')
    cce_19 = models.CharField(db_column='CCE_19', max_length=15, default='')
    invdtaamt_0 = models.DecimalField(db_column='INVDTAAMT_0', max_digits=20, decimal_places=5, default=0)
    invdtaamt_1 = models.DecimalField(db_column='INVDTAAMT_1', max_digits=20, decimal_places=5, default=0)
    invdtaamt_2 = models.DecimalField(db_column='INVDTAAMT_2', max_digits=20, decimal_places=5, default=0)
    invdtaamt_3 = models.DecimalField(db_column='INVDTAAMT_3', max_digits=20, decimal_places=5, default=0)
    invdtaamt_4 = models.DecimalField(db_column='INVDTAAMT_4', max_digits=20, decimal_places=5, default=0)
    invdtaamt_5 = models.DecimalField(db_column='INVDTAAMT_5', max_digits=20, decimal_places=5, default=0)
    invdtaamt_6 = models.DecimalField(db_column='INVDTAAMT_6', max_digits=20, decimal_places=5, default=0)
    invdtaamt_7 = models.DecimalField(db_column='INVDTAAMT_7', max_digits=20, decimal_places=5, default=0)
    invdtaamt_8 = models.DecimalField(db_column='INVDTAAMT_8', max_digits=20, decimal_places=5, default=0)
    invdtaamt_9 = models.DecimalField(db_column='INVDTAAMT_9', max_digits=20, decimal_places=5, default=0)
    invdtaamt_10 = models.DecimalField(db_column='INVDTAAMT_10', max_digits=20, decimal_places=5, default=0)
    invdtaamt_11 = models.DecimalField(db_column='INVDTAAMT_11', max_digits=20, decimal_places=5, default=0)
    invdtaamt_12 = models.DecimalField(db_column='INVDTAAMT_12', max_digits=20, decimal_places=5, default=0)
    invdtaamt_13 = models.DecimalField(db_column='INVDTAAMT_13', max_digits=20, decimal_places=5, default=0)
    invdtaamt_14 = models.DecimalField(db_column='INVDTAAMT_14', max_digits=20, decimal_places=5, default=0)
    invdtaamt_15 = models.DecimalField(db_column='INVDTAAMT_15', max_digits=20, decimal_places=5, default=0)
    invdtaamt_16 = models.DecimalField(db_column='INVDTAAMT_16', max_digits=20, decimal_places=5, default=0)
    invdtaamt_17 = models.DecimalField(db_column='INVDTAAMT_17', max_digits=20, decimal_places=5, default=0)
    invdtaamt_18 = models.DecimalField(db_column='INVDTAAMT_18', max_digits=20, decimal_places=5, default=0)
    invdtaamt_19 = models.DecimalField(db_column='INVDTAAMT_19', max_digits=20, decimal_places=5, default=0)
    invdtaamt_20 = models.DecimalField(db_column='INVDTAAMT_20', max_digits=20, decimal_places=5, default=0)
    invdtaamt_21 = models.DecimalField(db_column='INVDTAAMT_21', max_digits=20, decimal_places=5, default=0)
    invdtaamt_22 = models.DecimalField(db_column='INVDTAAMT_22', max_digits=20, decimal_places=5, default=0)
    invdtaamt_23 = models.DecimalField(db_column='INVDTAAMT_23', max_digits=20, decimal_places=5, default=0)
    invdtaamt_24 = models.DecimalField(db_column='INVDTAAMT_24', max_digits=20, decimal_places=5, default=0)
    invdtaamt_25 = models.DecimalField(db_column='INVDTAAMT_25', max_digits=20, decimal_places=5, default=0)
    invdtaamt_26 = models.DecimalField(db_column='INVDTAAMT_26', max_digits=20, decimal_places=5, default=0)
    invdtaamt_27 = models.DecimalField(db_column='INVDTAAMT_27', max_digits=20, decimal_places=5, default=0)
    invdtaamt_28 = models.DecimalField(db_column='INVDTAAMT_28', max_digits=20, decimal_places=5, default=0)
    invdtaamt_29 = models.DecimalField(db_column='INVDTAAMT_29', max_digits=20, decimal_places=5, default=0)
    invdtatyp_0 = models.SmallIntegerField(db_column='INVDTATYP_0', default=0)
    invdtatyp_1 = models.SmallIntegerField(db_column='INVDTATYP_1', default=0)
    invdtatyp_2 = models.SmallIntegerField(db_column='INVDTATYP_2', default=0)
    invdtatyp_3 = models.SmallIntegerField(db_column='INVDTATYP_3', default=0)
    invdtatyp_4 = models.SmallIntegerField(db_column='INVDTATYP_4', default=0)
    invdtatyp_5 = models.SmallIntegerField(db_column='INVDTATYP_5', default=0)
    invdtatyp_6 = models.SmallIntegerField(db_column='INVDTATYP_6', default=0)
    invdtatyp_7 = models.SmallIntegerField(db_column='INVDTATYP_7', default=0)
    invdtatyp_8 = models.SmallIntegerField(db_column='INVDTATYP_8', default=0)
    invdtatyp_9 = models.SmallIntegerField(db_column='INVDTATYP_9', default=0)
    invdtatyp_10 = models.SmallIntegerField(db_column='INVDTATYP_10', default=0)
    invdtatyp_11 = models.SmallIntegerField(db_column='INVDTATYP_11', default=0)
    invdtatyp_12 = models.SmallIntegerField(db_column='INVDTATYP_12', default=0)
    invdtatyp_13 = models.SmallIntegerField(db_column='INVDTATYP_13', default=0)
    invdtatyp_14 = models.SmallIntegerField(db_column='INVDTATYP_14', default=0)
    invdtatyp_15 = models.SmallIntegerField(db_column='INVDTATYP_15', default=0)
    invdtatyp_16 = models.SmallIntegerField(db_column='INVDTATYP_16', default=0)
    invdtatyp_17 = models.SmallIntegerField(db_column='INVDTATYP_17', default=0)
    invdtatyp_18 = models.SmallIntegerField(db_column='INVDTATYP_18', default=0)
    invdtatyp_19 = models.SmallIntegerField(db_column='INVDTATYP_19', default=0)
    invdtatyp_20 = models.SmallIntegerField(db_column='INVDTATYP_20', default=0)
    invdtatyp_21 = models.SmallIntegerField(db_column='INVDTATYP_21', default=0)
    invdtatyp_22 = models.SmallIntegerField(db_column='INVDTATYP_22', default=0)
    invdtatyp_23 = models.SmallIntegerField(db_column='INVDTATYP_23', default=0)
    invdtatyp_24 = models.SmallIntegerField(db_column='INVDTATYP_24', default=0)
    invdtatyp_25 = models.SmallIntegerField(db_column='INVDTATYP_25', default=0)
    invdtatyp_26 = models.SmallIntegerField(db_column='INVDTATYP_26', default=0)
    invdtatyp_27 = models.SmallIntegerField(db_column='INVDTATYP_27', default=0)
    invdtatyp_28 = models.SmallIntegerField(db_column='INVDTATYP_28', default=0)
    invdtatyp_29 = models.SmallIntegerField(db_column='INVDTATYP_29', default=0)
    invdta_0 = models.SmallIntegerField(db_column='INVDTA_0', default=0)
    invdta_1 = models.SmallIntegerField(db_column='INVDTA_1', default=0)
    invdta_2 = models.SmallIntegerField(db_column='INVDTA_2', default=0)
    invdta_3 = models.SmallIntegerField(db_column='INVDTA_3', default=0)
    invdta_4 = models.SmallIntegerField(db_column='INVDTA_4', default=0)
    invdta_5 = models.SmallIntegerField(db_column='INVDTA_5', default=0)
    invdta_6 = models.SmallIntegerField(db_column='INVDTA_6', default=0)
    invdta_7 = models.SmallIntegerField(db_column='INVDTA_7', default=0)
    invdta_8 = models.SmallIntegerField(db_column='INVDTA_8', default=0)
    invdta_9 = models.SmallIntegerField(db_column='INVDTA_9', default=0)
    invdta_10 = models.SmallIntegerField(db_column='INVDTA_10', default=0)
    invdta_11 = models.SmallIntegerField(db_column='INVDTA_11', default=0)
    invdta_12 = models.SmallIntegerField(db_column='INVDTA_12', default=0)
    invdta_13 = models.SmallIntegerField(db_column='INVDTA_13', default=0)
    invdta_14 = models.SmallIntegerField(db_column='INVDTA_14', default=0)
    invdta_15 = models.SmallIntegerField(db_column='INVDTA_15', default=0)
    invdta_16 = models.SmallIntegerField(db_column='INVDTA_16', default=0)
    invdta_17 = models.SmallIntegerField(db_column='INVDTA_17', default=0)
    invdta_18 = models.SmallIntegerField(db_column='INVDTA_18', default=0)
    invdta_19 = models.SmallIntegerField(db_column='INVDTA_19', default=0)
    invdta_20 = models.SmallIntegerField(db_column='INVDTA_20', default=0)
    invdta_21 = models.SmallIntegerField(db_column='INVDTA_21', default=0)
    invdta_22 = models.SmallIntegerField(db_column='INVDTA_22', default=0)
    invdta_23 = models.SmallIntegerField(db_column='INVDTA_23', default=0)
    invdta_24 = models.SmallIntegerField(db_column='INVDTA_24', default=0)
    invdta_25 = models.SmallIntegerField(db_column='INVDTA_25', default=0)
    invdta_26 = models.SmallIntegerField(db_column='INVDTA_26', default=0)
    invdta_27 = models.SmallIntegerField(db_column='INVDTA_27', default=0)
    invdta_28 = models.SmallIntegerField(db_column='INVDTA_28', default=0)
    invdta_29 = models.SmallIntegerField(db_column='INVDTA_29', default=0)
    sfisstcod_0 = models.CharField(db_column='SFISSTCOD_0', max_length=20, default='')
    sfisstcod_1 = models.CharField(db_column='SFISSTCOD_1', max_length=20, default='')
    sfisstcod_2 = models.CharField(db_column='SFISSTCOD_2', max_length=20, default='')
    sfisstcod_3 = models.CharField(db_column='SFISSTCOD_3', max_length=20, default='')
    sfisstcod_4 = models.CharField(db_column='SFISSTCOD_4', max_length=20, default='')
    sfisstcod_5 = models.CharField(db_column='SFISSTCOD_5', max_length=20, default='')
    sfisstcod_6 = models.CharField(db_column='SFISSTCOD_6', max_length=20, default='')
    sfisstcod_7 = models.CharField(db_column='SFISSTCOD_7', max_length=20, default='')
    sfisstcod_8 = models.CharField(db_column='SFISSTCOD_8', max_length=20, default='')
    sfisstcod_9 = models.CharField(db_column='SFISSTCOD_9', max_length=20, default='')
    sfisstcod_10 = models.CharField(db_column='SFISSTCOD_10', max_length=20, default='')
    sfisstcod_11 = models.CharField(db_column='SFISSTCOD_11', max_length=20, default='')
    sfisstcod_12 = models.CharField(db_column='SFISSTCOD_12', max_length=20, default='')
    sfisstcod_13 = models.CharField(db_column='SFISSTCOD_13', max_length=20, default='')
    sfisstcod_14 = models.CharField(db_column='SFISSTCOD_14', max_length=20, default='')
    sfisstcod_15 = models.CharField(db_column='SFISSTCOD_15', max_length=20, default='')
    sfisstcod_16 = models.CharField(db_column='SFISSTCOD_16', max_length=20, default='')
    sfisstcod_17 = models.CharField(db_column='SFISSTCOD_17', max_length=20, default='')
    sfisstcod_18 = models.CharField(db_column='SFISSTCOD_18', max_length=20, default='')
    sfisstcod_19 = models.CharField(db_column='SFISSTCOD_19', max_length=20, default='')
    sfisstcod_20 = models.CharField(db_column='SFISSTCOD_20', max_length=20, default='')
    sfisstcod_21 = models.CharField(db_column='SFISSTCOD_21', max_length=20, default='')
    sfisstcod_22 = models.CharField(db_column='SFISSTCOD_22', max_length=20, default='')
    sfisstcod_23 = models.CharField(db_column='SFISSTCOD_23', max_length=20, default='')
    sfisstcod_24 = models.CharField(db_column='SFISSTCOD_24', max_length=20, default='')
    sfisstcod_25 = models.CharField(db_column='SFISSTCOD_25', max_length=20, default='')
    sfisstcod_26 = models.CharField(db_column='SFISSTCOD_26', max_length=20, default='')
    sfisstcod_27 = models.CharField(db_column='SFISSTCOD_27', max_length=20, default='')
    sfisstcod_28 = models.CharField(db_column='SFISSTCOD_28', max_length=20, default='')
    sfisstcod_29 = models.CharField(db_column='SFISSTCOD_29', max_length=20, default='')
    typmac_0 = models.SmallIntegerField(db_column='TYPMAC_0', default=0)
    macflt_0 = models.CharField(db_column='MACFLT_0', max_length=20, default='')
    macfltint_0 = models.SmallIntegerField(db_column='MACFLTINT_0', default=0)
    numfuldes_0 = models.CharField(db_column='NUMFULDES_0', max_length=30, default='')
    sredesflg_0 = models.SmallIntegerField(db_column='SREDESFLG_0', default=0)
    sreinvflg_0 = models.SmallIntegerField(db_column='SREINVFLG_0', default=0)
    tskrepcre_0 = models.SmallIntegerField(db_column='TSKREPCRE_0', default=0)
    sregralev_0 = models.CharField(db_column='SREGRALEV_0', max_length=20, default='')
    srepiolev_0 = models.CharField(db_column='SREPIOLEV_0', max_length=20, default='')
    conspt_0 = models.CharField(db_column='CONSPT_0', max_length=20, default='')
    conspttyp_0 = models.CharField(db_column='CONSPTTYP_0', max_length=8, default='')
    consptflg_0 = models.SmallIntegerField(db_column='CONSPTFLG_0', default=0)
    srepblgrp_0 = models.CharField(db_column='SREPBLGRP_0', max_length=20, default='')
    sretimspg_0 = models.SmallIntegerField(db_column='SRETIMSPG_0', default=0)
    timspgday_0 = models.IntegerField(db_column='TIMSPGDAY_0', default=0)
    timspghou_0 = models.IntegerField(db_column='TIMSPGHOU_0', default=0)
    timspgmnt_0 = models.IntegerField(db_column='TIMSPGMNT_0', default=0)
    ctimspgday_0 = models.IntegerField(db_column='CTIMSPGDAY_0', default=0)
    ctimspghou_0 = models.IntegerField(db_column='CTIMSPGHOU_0', default=0)
    ctimspgmnt_0 = models.IntegerField(db_column='CTIMSPGMNT_0', default=0)
    sreesc_0 = models.SmallIntegerField(db_column='SREESC_0', default=0)
    sreesc2_0 = models.SmallIntegerField(db_column='SREESC2_0', default=0)
    sreesc3_0 = models.SmallIntegerField(db_column='SREESC3_0', default=0)
    manupd_0 = models.SmallIntegerField(db_column='MANUPD_0', default=0)
    srelok_0 = models.SmallIntegerField(db_column='SRELOK_0', default=0)
    sreresren_0 = models.CharField(db_column='SRERESREN_0', max_length=80, default='')
    ovrcov_0 = models.SmallIntegerField(db_column='OVRCOV_0', default=0)
    ovrcovren_0 = models.SmallIntegerField(db_column='OVRCOVREN_0', default=0)
    ovrcovtyp_0 = models.CharField(db_column='OVRCOVTYP_0', max_length=8, default='')
    srecov_0 = models.SmallIntegerField(db_column='SRECOV_0', default=0)
    sretypcov_0 = models.SmallIntegerField(db_column='SRETYPCOV_0', default=0)
    srecovnum_0 = models.CharField(db_column='SRECOVNUM_0', max_length=20, default='')
    srecovaut_0 = models.SmallIntegerField(db_column='SRECOVAUT_0', default=0)
    srecovaus_0 = models.CharField(db_column='SRECOVAUS_0', max_length=5, default='')
    covauscla_0 = models.CharField(db_column='COVAUSCLA_0', max_length=30, default='')
    srecovctl_0 = models.CharField(db_column='SRECOVCTL_0', max_length=5, default='')
    solnum_0 = models.CharField(db_column='SOLNUM_0', max_length=20, default='')
    rep_0 = models.CharField(db_column='REP_0', max_length=5, default='')
    sreori_0 = models.SmallIntegerField(db_column='SREORI_0', default=0)
    sreorivcr_0 = models.CharField(db_column='SREORIVCR_0', max_length=20, default='')
    sreorivcrl_0 = models.IntegerField(db_column='SREORIVCRL_0', default=0)
    sretpl_0 = models.CharField(db_column='SRETPL_0', max_length=20, default='')
    tsdcod_0 = models.CharField(db_column='TSDCOD_0', max_length=20, default='')
    tsdcod_1 = models.CharField(db_column='TSDCOD_1', max_length=20, default='')
    tsdcod_2 = models.CharField(db_column='TSDCOD_2', max_length=20, default='')
    tsdcod_3 = models.CharField(db_column='TSDCOD_3', max_length=20, default='')
    tsdcod_4 = models.CharField(db_column='TSDCOD_4', max_length=20, default='')
    trscod_0 = models.CharField(db_column='TRSCOD_0', max_length=20, default='')
    entcod_0 = models.CharField(db_column='ENTCOD_0', max_length=5, default='')
    trsfam_0 = models.CharField(db_column='TRSFAM_0', max_length=20, default='')
    nbrmanupd_0 = models.IntegerField(db_column='NBRMANUPD_0', default=0)

    class Meta:
        managed = False
        db_table = 'SERREQUEST'
        unique_together = (
            ('create_date', 'service_number'),
            ('ticket_date', 'ticket_hour', 'title', 'service_number'),
        )

        verbose_name = 'Ticket'
        verbose_name_plural = 'Tickets'

    def __str__(self):
        return self.service_number
