from django.conf import settings
from django.db import models
from django.utils import timezone


class Group(models.Model):
    company = models.CharField(db_column='CPY_0', max_length=5)
    company_name = models.CharField(db_column='CPYNAM_0', max_length=35)
    european_vat_number = models.CharField(db_column='EECNUM_0', max_length=20)
    country = models.CharField(db_column='CRY_0', max_length=3)
    site = models.CharField(db_column='FCY_0', max_length=5)
    site_name = models.CharField(db_column='FCYNAM_0', max_length=35)
    site_country = models.CharField(db_column='FCYCRY_0', max_length=3)

    class Meta:
        managed = False
        db_table = 'YCOMPANY'
        verbose_name = 'Group'
        verbose_name_plural = 'Groups'


class Company(models.Model):
    id = models.BigAutoField(db_column='ROWID', primary_key=True)
    company = models.CharField(db_column='CPY_0', max_length=5, default='')
    company_name = models.CharField(db_column='CPYNAM_0', max_length=35, default='')
    legislation = models.CharField(db_column='LEG_0', max_length=20, default='')
    country = models.CharField(db_column='CRY_0', max_length=3, default='')
    address = models.CharField(db_column='BPAADD_0', max_length=5, default='')
    european_vat_number = models.CharField(db_column='EECNUM_0', max_length=20, default='')

    cpysho_0 = models.CharField(db_column='CPYSHO_0', max_length=10, default='')
    cpylegflg_0 = models.SmallIntegerField(db_column='CPYLEGFLG_0', default=2)
    acm_0 = models.CharField(db_column='ACM_0', max_length=3, default='')
    maifcy_0 = models.CharField(db_column='MAIFCY_0', max_length=5, default='')
    crn_0 = models.CharField(db_column='CRN_0', max_length=20, default='')
    naf_0 = models.CharField(db_column='NAF_0', max_length=10, default='')
    nid_0 = models.CharField(db_column='NID_0', max_length=80, default='')
    cpylog_0 = models.CharField(db_column='CPYLOG_0', max_length=10, default='')
    rgcamt_0 = models.DecimalField(db_column='RGCAMT_0', max_digits=20, decimal_places=5, default=0)
    rgccur_0 = models.CharField(db_column='RGCCUR_0', max_length=3, default='')
    cntnam_0 = models.CharField(db_column='CNTNAM_0', max_length=15, default='')
    bidnum_0 = models.CharField(db_column='BIDNUM_0', max_length=30, default='')
    acccod_0 = models.CharField(db_column='ACCCOD_0', max_length=10, default='')
    divcod_0 = models.CharField(db_column='DIVCOD_0', max_length=1, default='')
    fdrx3_0 = models.CharField(db_column='FDRX3_0', max_length=1, default='')
    strper_0 = models.DateTimeField(db_column='STRPER_0', default=settings.DEFAULT_LEGACY_DATE)
    acccur_0 = models.CharField(db_column='ACCCUR_0', max_length=3, default='')
    die_0 = models.CharField(db_column='DIE_0', max_length=3, default='')
    die_1 = models.CharField(db_column='DIE_1', max_length=3, default='')
    die_2 = models.CharField(db_column='DIE_2', max_length=3, default='')
    die_3 = models.CharField(db_column='DIE_3', max_length=3, default='')
    die_4 = models.CharField(db_column='DIE_4', max_length=3, default='')
    die_5 = models.CharField(db_column='DIE_5', max_length=3, default='')
    die_6 = models.CharField(db_column='DIE_6', max_length=3, default='')
    die_7 = models.CharField(db_column='DIE_7', max_length=3, default='')
    die_8 = models.CharField(db_column='DIE_8', max_length=3, default='')
    die_9 = models.CharField(db_column='DIE_9', max_length=3, default='')
    die_10 = models.CharField(db_column='DIE_10', max_length=3, default='')
    die_11 = models.CharField(db_column='DIE_11', max_length=3, default='')
    die_12 = models.CharField(db_column='DIE_12', max_length=3, default='')
    die_13 = models.CharField(db_column='DIE_13', max_length=3, default='')
    die_14 = models.CharField(db_column='DIE_14', max_length=3, default='')
    die_15 = models.CharField(db_column='DIE_15', max_length=3, default='')
    die_16 = models.CharField(db_column='DIE_16', max_length=3, default='')
    die_17 = models.CharField(db_column='DIE_17', max_length=3, default='')
    die_18 = models.CharField(db_column='DIE_18', max_length=3, default='')
    die_19 = models.CharField(db_column='DIE_19', max_length=3, default='')
    kact_0 = models.CharField(db_column='KACT_0', max_length=20, default='')
    numadd_0 = models.SmallIntegerField(db_column='NUMADD_0', default=0)
    oricerflg_0 = models.SmallIntegerField(db_column='ORICERFLG_0', default=0)
    eorinum_0 = models.CharField(db_column='EORINUM_0', max_length=35, default='')
    obydie_0 = models.SmallIntegerField(db_column='OBYDIE_0', default=0)
    obydie_1 = models.SmallIntegerField(db_column='OBYDIE_1', default=0)
    obydie_2 = models.SmallIntegerField(db_column='OBYDIE_2', default=0)
    obydie_3 = models.SmallIntegerField(db_column='OBYDIE_3', default=0)
    obydie_4 = models.SmallIntegerField(db_column='OBYDIE_4', default=0)
    obydie_5 = models.SmallIntegerField(db_column='OBYDIE_5', default=0)
    obydie_6 = models.SmallIntegerField(db_column='OBYDIE_6', default=0)
    obydie_7 = models.SmallIntegerField(db_column='OBYDIE_7', default=0)
    obydie_8 = models.SmallIntegerField(db_column='OBYDIE_8', default=0)
    obydie_9 = models.SmallIntegerField(db_column='OBYDIE_9', default=0)
    obydie_10 = models.SmallIntegerField(db_column='OBYDIE_10', default=0)
    obydie_11 = models.SmallIntegerField(db_column='OBYDIE_11', default=0)
    obydie_12 = models.SmallIntegerField(db_column='OBYDIE_12', default=0)
    obydie_13 = models.SmallIntegerField(db_column='OBYDIE_13', default=0)
    obydie_14 = models.SmallIntegerField(db_column='OBYDIE_14', default=0)
    obydie_15 = models.SmallIntegerField(db_column='OBYDIE_15', default=0)
    obydie_16 = models.SmallIntegerField(db_column='OBYDIE_16', default=0)
    obydie_17 = models.SmallIntegerField(db_column='OBYDIE_17', default=0)
    obydie_18 = models.SmallIntegerField(db_column='OBYDIE_18', default=0)
    obydie_19 = models.SmallIntegerField(db_column='OBYDIE_19', default=0)
    rexnum_0 = models.CharField(db_column='REXNUM_0', max_length=30, default='')
    stafed_0 = models.CharField(db_column='STAFED_0', max_length=1, default='')
    dacdie_0 = models.SmallIntegerField(db_column='DACDIE_0', default=0)
    dacdie_1 = models.SmallIntegerField(db_column='DACDIE_1', default=0)
    dacdie_2 = models.SmallIntegerField(db_column='DACDIE_2', default=0)
    dacdie_3 = models.SmallIntegerField(db_column='DACDIE_3', default=0)
    dacdie_4 = models.SmallIntegerField(db_column='DACDIE_4', default=0)
    dacdie_5 = models.SmallIntegerField(db_column='DACDIE_5', default=0)
    dacdie_6 = models.SmallIntegerField(db_column='DACDIE_6', default=0)
    dacdie_7 = models.SmallIntegerField(db_column='DACDIE_7', default=0)
    dacdie_8 = models.SmallIntegerField(db_column='DACDIE_8', default=0)
    dacdie_9 = models.SmallIntegerField(db_column='DACDIE_9', default=0)
    dacdie_10 = models.SmallIntegerField(db_column='DACDIE_10', default=0)
    dacdie_11 = models.SmallIntegerField(db_column='DACDIE_11', default=0)
    dacdie_12 = models.SmallIntegerField(db_column='DACDIE_12', default=0)
    dacdie_13 = models.SmallIntegerField(db_column='DACDIE_13', default=0)
    dacdie_14 = models.SmallIntegerField(db_column='DACDIE_14', default=0)
    dacdie_15 = models.SmallIntegerField(db_column='DACDIE_15', default=0)
    dacdie_16 = models.SmallIntegerField(db_column='DACDIE_16', default=0)
    dacdie_17 = models.SmallIntegerField(db_column='DACDIE_17', default=0)
    dacdie_18 = models.SmallIntegerField(db_column='DACDIE_18', default=0)
    dacdie_19 = models.SmallIntegerField(db_column='DACDIE_19', default=0)
    grucod_0 = models.CharField(db_column='GRUCOD_0', max_length=1, default='')
    cce_0 = models.CharField(db_column='CCE_0', max_length=15, default='')
    cce_1 = models.CharField(db_column='CCE_1', max_length=15, default='')
    cce_2 = models.CharField(db_column='CCE_2', max_length=15, default='')
    cce_3 = models.CharField(db_column='CCE_3', max_length=15, default='')
    cce_4 = models.CharField(db_column='CCE_4', max_length=15, default='')
    cce_5 = models.CharField(db_column='CCE_5', max_length=15, default='')
    cce_6 = models.CharField(db_column='CCE_6', max_length=15, default='')
    cce_7 = models.CharField(db_column='CCE_7', max_length=15, default='')
    cce_8 = models.CharField(db_column='CCE_8', max_length=15, default='')
    cce_9 = models.CharField(db_column='CCE_9', max_length=15, default='')
    cce_10 = models.CharField(db_column='CCE_10', max_length=15, default='')
    cce_11 = models.CharField(db_column='CCE_11', max_length=15, default='')
    cce_12 = models.CharField(db_column='CCE_12', max_length=15, default='')
    cce_13 = models.CharField(db_column='CCE_13', max_length=15, default='')
    cce_14 = models.CharField(db_column='CCE_14', max_length=15, default='')
    cce_15 = models.CharField(db_column='CCE_15', max_length=15, default='')
    cce_16 = models.CharField(db_column='CCE_16', max_length=15, default='')
    cce_17 = models.CharField(db_column='CCE_17', max_length=15, default='')
    cce_18 = models.CharField(db_column='CCE_18', max_length=15, default='')
    cce_19 = models.CharField(db_column='CCE_19', max_length=15, default='')
    plistc_0 = models.CharField(db_column='PLISTC_0', max_length=10, default='')
    rtzflg_0 = models.SmallIntegerField(db_column='RTZFLG_0', default=0)
    agtpcp_0 = models.SmallIntegerField(db_column='AGTPCP_0', default=0)
    vaccpy_0 = models.CharField(db_column='VACCPY_0', max_length=1, default='')
    dcldirbalpay_0 = models.SmallIntegerField(db_column='DCLDIRBALPAY_0', default=0)
    bdfecocod_0 = models.CharField(db_column='BDFECOCOD_0', max_length=10, default='')
    ausfinsrv_0 = models.CharField(db_column='AUSFINSRV_0', max_length=1, default='')
    gerdefval_0 = models.SmallIntegerField(db_column='GERDEFVAL_0', default=0)
    gereecnum_0 = models.CharField(db_column='GEREECNUM_0', max_length=1, default='')
    gertaxcen_0 = models.CharField(db_column='GERTAXCEN_0', max_length=1, default='')
    gertaxidt_0 = models.CharField(db_column='GERTAXIDT_0', max_length=1, default='')
    gercodelma5_0 = models.CharField(db_column='GERCODELMA5_0', max_length=1, default='')
    gerptp_0 = models.CharField(db_column='GERPTP_0', max_length=1, default='')
    spabpctsd_0 = models.DecimalField(db_column='SPABPCTSD_0', max_digits=28, decimal_places=8)
    spabpstsd_0 = models.DecimalField(db_column='SPABPSTSD_0', max_digits=28, decimal_places=8)
    spayeatsd_0 = models.DecimalField(db_column='SPAYEATSD_0', max_digits=28, decimal_places=8)
    porctfacn_0 = models.CharField(db_column='PORCTFACN_0', max_length=9, default='')
    porcpyact_0 = models.CharField(db_column='PORCPYACT_0', max_length=5, default='')
    pordclper_0 = models.SmallIntegerField(db_column='PORDCLPER_0', default=0)
    porlrc_0 = models.CharField(db_column='PORLRC_0', max_length=9, default='')
    porhqr_0 = models.SmallIntegerField(db_column='PORHQR_0', default=0)
    porcpyactdet_0 = models.CharField(db_column='PORCPYACTDET_0', max_length=5, default='')
    porfindpr_0 = models.CharField(db_column='PORFINDPR_0', max_length=9, default='')
    scinum_0 = models.CharField(db_column='SCINUM_0', max_length=35, default='')
    porcpyacttyp_0 = models.SmallIntegerField(db_column='PORCPYACTTYP_0', default=0)
    porsiminviss_0 = models.SmallIntegerField(db_column='PORSIMINVISS_0', default=0)
    poramtserinv_0 = models.DecimalField(db_column='PORAMTSERINV_0', max_digits=14, decimal_places=3)
    poramtitminv_0 = models.DecimalField(db_column='PORAMTITMINV_0', max_digits=14, decimal_places=3)
    porresfiscda_0 = models.CharField(db_column='PORRESFISCDA_0', max_length=5, default='')
    ssttaxact_0 = models.SmallIntegerField(db_column='SSTTAXACT_0', default=0)
    sstcpy_0 = models.CharField(db_column='SSTCPY_0', max_length=1, default='')
    sfinum_0 = models.SmallIntegerField(db_column='SFINUM_0', default=0)
    commtype_0 = models.SmallIntegerField(db_column='COMMTYPE_0', default=0)
    commtype_1 = models.SmallIntegerField(db_column='COMMTYPE_1', default=0)
    commtype_2 = models.SmallIntegerField(db_column='COMMTYPE_2', default=0)
    commtype_3 = models.SmallIntegerField(db_column='COMMTYPE_3', default=0)
    commtype_4 = models.SmallIntegerField(db_column='COMMTYPE_4', default=0)
    commtype_5 = models.SmallIntegerField(db_column='COMMTYPE_5', default=0)
    commtype_6 = models.SmallIntegerField(db_column='COMMTYPE_6', default=0)
    commtype_7 = models.SmallIntegerField(db_column='COMMTYPE_7', default=0)
    commtype_8 = models.SmallIntegerField(db_column='COMMTYPE_8', default=0)
    strdat_0 = models.DateTimeField(db_column='STRDAT_0', default=settings.DEFAULT_LEGACY_DATE)
    strdat_1 = models.DateTimeField(db_column='STRDAT_1', default=settings.DEFAULT_LEGACY_DATE)
    strdat_2 = models.DateTimeField(db_column='STRDAT_2', default=settings.DEFAULT_LEGACY_DATE)
    strdat_3 = models.DateTimeField(db_column='STRDAT_3', default=settings.DEFAULT_LEGACY_DATE)
    strdat_4 = models.DateTimeField(db_column='STRDAT_4', default=settings.DEFAULT_LEGACY_DATE)
    strdat_5 = models.DateTimeField(db_column='STRDAT_5', default=settings.DEFAULT_LEGACY_DATE)
    strdat_6 = models.DateTimeField(db_column='STRDAT_6', default=settings.DEFAULT_LEGACY_DATE)
    strdat_7 = models.DateTimeField(db_column='STRDAT_7', default=settings.DEFAULT_LEGACY_DATE)
    strdat_8 = models.DateTimeField(db_column='STRDAT_8', default=settings.DEFAULT_LEGACY_DATE)
    enddat_0 = models.DateTimeField(db_column='ENDDAT_0', default=settings.DEFAULT_LEGACY_DATE)
    enddat_1 = models.DateTimeField(db_column='ENDDAT_1', default=settings.DEFAULT_LEGACY_DATE)
    enddat_2 = models.DateTimeField(db_column='ENDDAT_2', default=settings.DEFAULT_LEGACY_DATE)
    enddat_3 = models.DateTimeField(db_column='ENDDAT_3', default=settings.DEFAULT_LEGACY_DATE)
    enddat_4 = models.DateTimeField(db_column='ENDDAT_4', default=settings.DEFAULT_LEGACY_DATE)
    enddat_5 = models.DateTimeField(db_column='ENDDAT_5', default=settings.DEFAULT_LEGACY_DATE)
    enddat_6 = models.DateTimeField(db_column='ENDDAT_6', default=settings.DEFAULT_LEGACY_DATE)
    enddat_7 = models.DateTimeField(db_column='ENDDAT_7', default=settings.DEFAULT_LEGACY_DATE)
    enddat_8 = models.DateTimeField(db_column='ENDDAT_8', default=settings.DEFAULT_LEGACY_DATE)
    taxagcnum_0 = models.CharField(db_column='TAXAGCNUM_0', max_length=1, default='')
    taxagcnam_0 = models.CharField(db_column='TAXAGCNAM_0', max_length=1, default='')
    taxagnnum_0 = models.CharField(db_column='TAXAGNNUM_0', max_length=1, default='')
    taxagnnam_0 = models.CharField(db_column='TAXAGNNAM_0', max_length=1, default='')
    aracpynam_0 = models.CharField(db_column='ARACPYNAM_0', max_length=1, default='')
    gosirefnum_0 = models.CharField(db_column='GOSIREFNUM_0', max_length=1, default='')
    sct1_0 = models.CharField(db_column='SCT1_0', max_length=20, default='')
    molid_0 = models.CharField(db_column='MOLID_0', max_length=1, default='')
    sct2_0 = models.CharField(db_column='SCT2_0', max_length=20, default='')
    trecpy_0 = models.CharField(db_column='TRECPY_0', max_length=1, default='')
    trecpy2_0 = models.CharField(db_column='TRECPY2_0', max_length=1, default='')
    impcpy_0 = models.SmallIntegerField(db_column='IMPCPY_0', default=0)
    bdo_0 = models.CharField(db_column='BDO_0', max_length=1, default='')
    agreement_0 = models.CharField(db_column='AGREEMENT_0', max_length=1, default='')
    serviceid_0 = models.CharField(db_column='SERVICEID_0', max_length=1, default='')
    iniper_0 = models.DateTimeField(db_column='INIPER_0', default=settings.DEFAULT_LEGACY_DATE)
    finper_0 = models.DateTimeField(db_column='FINPER_0', default=settings.DEFAULT_LEGACY_DATE)
    solfin_0 = models.CharField(db_column='SOLFIN_0', max_length=1, default='')
    amtfin_0 = models.DecimalField(db_column='AMTFIN_0', max_digits=28, decimal_places=8, default=0)

    create_user = models.CharField(db_column='CREUSR_0', max_length=5, default='INTER')
    create_date = models.DateTimeField(db_column='CREDAT_0', default=timezone.now)
    update_user = models.CharField(db_column='UPDUSR_0', max_length=5, default='INTER')
    update_date = models.DateTimeField(db_column='UPDDAT_0', default=timezone.now)
    create_datetime = models.DateTimeField(db_column='CREDATTIM_0', auto_now_add=True)
    update_datetime = models.DateTimeField(db_column='UPDDATTIM_0', auto_now=True)

    updtick = models.IntegerField(db_column='UPDTICK_0', default=1)
    auuid = models.BinaryField(db_column='AUUID_0')

    class Meta:
        managed = False
        db_table = 'COMPANY'
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'


class Facility(models.Model):
    id = models.BigAutoField(db_column='ROWID', primary_key=True)
    facility = models.CharField(db_column='FCY_0', max_length=5, default='')
    facility_name = models.CharField(db_column='FCYNAM_0', max_length=35, default='')
    country = models.CharField(db_column='CRY_0', max_length=3, default='')
    is_sales = models.SmallIntegerField(db_column='SALFLG_0', default=1)
    is_purchase = models.SmallIntegerField(db_column='PURFLG_0', default=1)
    is_financial = models.SmallIntegerField(db_column='FINFLG_0', default=1)
    company = models.CharField(db_column='LEGCPY_0', max_length=5, default='')
    legislation = models.CharField(db_column='LEG_0', max_length=20, default='')

    fcysho_0 = models.CharField(db_column='FCYSHO_0', max_length=10, default='')
    crn_0 = models.CharField(db_column='CRN_0', max_length=20, default='')
    naf_0 = models.CharField(db_column='NAF_0', max_length=10, default='')
    bptnum_0 = models.CharField(db_column='BPTNUM_0', max_length=10, default='')
    mfgflg_0 = models.SmallIntegerField(db_column='MFGFLG_0', default=1)
    wrhflg_0 = models.SmallIntegerField(db_column='WRHFLG_0', default=1)
    finrspfcy_0 = models.CharField(db_column='FINRSPFCY_0', max_length=5, default='')
    dadflg_0 = models.SmallIntegerField(db_column='DADFLG_0', default=0)
    payban_0 = models.CharField(db_column='PAYBAN_0', max_length=5, default='')
    bpaadd_0 = models.CharField(db_column='BPAADD_0', max_length=5, default='')
    bidnum_0 = models.CharField(db_column='BIDNUM_0', max_length=30, default='')
    cntnam_0 = models.CharField(db_column='CNTNAM_0', max_length=15, default='')
    dadfcy_0 = models.CharField(db_column='DADFCY_0', max_length=1, default='')
    acccod_0 = models.CharField(db_column='ACCCOD_0', max_length=10, default='')
    geocod_0 = models.CharField(db_column='GEOCOD_0', max_length=1, default='')
    eorinum_0 = models.CharField(db_column='EORINUM_0', max_length=35, default='')
    oricerflg_0 = models.SmallIntegerField(db_column='ORICERFLG_0', default=0)
    rexnum_0 = models.CharField(db_column='REXNUM_0', max_length=30, default='')
    die_0 = models.CharField(db_column='DIE_0', max_length=10, default='')
    die_1 = models.CharField(db_column='DIE_1', max_length=10, default='')
    die_2 = models.CharField(db_column='DIE_2', max_length=10, default='')
    die_3 = models.CharField(db_column='DIE_3', max_length=10, default='')
    die_4 = models.CharField(db_column='DIE_4', max_length=10, default='')
    die_5 = models.CharField(db_column='DIE_5', max_length=10, default='')
    die_6 = models.CharField(db_column='DIE_6', max_length=10, default='')
    die_7 = models.CharField(db_column='DIE_7', max_length=10, default='')
    die_8 = models.CharField(db_column='DIE_8', max_length=10, default='')
    die_9 = models.CharField(db_column='DIE_9', max_length=10, default='')
    die_10 = models.CharField(db_column='DIE_10', max_length=10, default='')
    die_11 = models.CharField(db_column='DIE_11', max_length=10, default='')
    die_12 = models.CharField(db_column='DIE_12', max_length=10, default='')
    die_13 = models.CharField(db_column='DIE_13', max_length=10, default='')
    die_14 = models.CharField(db_column='DIE_14', max_length=10, default='')
    die_15 = models.CharField(db_column='DIE_15', max_length=10, default='')
    die_16 = models.CharField(db_column='DIE_16', max_length=10, default='')
    die_17 = models.CharField(db_column='DIE_17', max_length=10, default='')
    die_18 = models.CharField(db_column='DIE_18', max_length=10, default='')
    die_19 = models.CharField(db_column='DIE_19', max_length=10, default='')
    insctyflg_0 = models.CharField(db_column='INSCTYFLG_0', max_length=1, default='')
    cce_0 = models.CharField(db_column='CCE_0', max_length=15, default='')
    cce_1 = models.CharField(db_column='CCE_1', max_length=15, default='')
    cce_2 = models.CharField(db_column='CCE_2', max_length=15, default='')
    cce_3 = models.CharField(db_column='CCE_3', max_length=15, default='')
    cce_4 = models.CharField(db_column='CCE_4', max_length=15, default='')
    cce_5 = models.CharField(db_column='CCE_5', max_length=15, default='')
    cce_6 = models.CharField(db_column='CCE_6', max_length=15, default='')
    cce_7 = models.CharField(db_column='CCE_7', max_length=15, default='')
    cce_8 = models.CharField(db_column='CCE_8', max_length=15, default='')
    cce_9 = models.CharField(db_column='CCE_9', max_length=15, default='')
    cce_10 = models.CharField(db_column='CCE_10', max_length=15, default='')
    cce_11 = models.CharField(db_column='CCE_11', max_length=15, default='')
    cce_12 = models.CharField(db_column='CCE_12', max_length=15, default='')
    cce_13 = models.CharField(db_column='CCE_13', max_length=15, default='')
    cce_14 = models.CharField(db_column='CCE_14', max_length=15, default='')
    cce_15 = models.CharField(db_column='CCE_15', max_length=15, default='')
    cce_16 = models.CharField(db_column='CCE_16', max_length=15, default='')
    cce_17 = models.CharField(db_column='CCE_17', max_length=15, default='')
    cce_18 = models.CharField(db_column='CCE_18', max_length=15, default='')
    cce_19 = models.CharField(db_column='CCE_19', max_length=15, default='')
    uvyday_0 = models.SmallIntegerField(db_column='UVYDAY_0', default=0)
    uvyday_1 = models.SmallIntegerField(db_column='UVYDAY_1', default=0)
    uvyday_2 = models.SmallIntegerField(db_column='UVYDAY_2', default=0)
    uvyday_3 = models.SmallIntegerField(db_column='UVYDAY_3', default=0)
    uvyday_4 = models.SmallIntegerField(db_column='UVYDAY_4', default=0)
    uvyday_5 = models.SmallIntegerField(db_column='UVYDAY_5', default=0)
    uvyday_6 = models.SmallIntegerField(db_column='UVYDAY_6', default=0)
    uvycod_0 = models.CharField(db_column='UVYCOD_0', max_length=5, default='')
    ivyflg_0 = models.SmallIntegerField(db_column='IVYFLG_0', default=0)
    ivyfcy_0 = models.CharField(db_column='IVYFCY_0', max_length=5, default='')
    wrhges_0 = models.SmallIntegerField(db_column='WRHGES_0', default=0)
    rcpwrh_0 = models.CharField(db_column='RCPWRH_0', max_length=5, default='')
    mfpwrh_0 = models.CharField(db_column='MFPWRH_0', max_length=5, default='')
    trawrh_0 = models.CharField(db_column='TRAWRH_0', max_length=5, default='')
    rtnwrh_0 = models.CharField(db_column='RTNWRH_0', max_length=5, default='')
    mfrwrh_0 = models.CharField(db_column='MFRWRH_0', max_length=5, default='')
    shiwrh_0 = models.CharField(db_column='SHIWRH_0', max_length=5, default='')
    mfgwrh_0 = models.CharField(db_column='MFGWRH_0', max_length=5, default='')
    trfwrh_0 = models.CharField(db_column='TRFWRH_0', max_length=5, default='')
    scowrh_0 = models.CharField(db_column='SCOWRH_0', max_length=5, default='')
    sccwrh_0 = models.CharField(db_column='SCCWRH_0', max_length=5, default='')
    spaopeigic_0 = models.SmallIntegerField(db_column='SPAOPEIGIC_0', default=0)
    strhou_0 = models.CharField(db_column='STRHOU_0', max_length=6, default='')
    endhou_0 = models.CharField(db_column='ENDHOU_0', max_length=6, default='')
    payflg_0 = models.SmallIntegerField(db_column='PAYFLG_0', default=0)
    hrmdadflg_0 = models.SmallIntegerField(db_column='HRMDADFLG_0', default=0)
    hrmdadfcy_0 = models.CharField(db_column='HRMDADFCY_0', max_length=1, default='')
    bpasge_0 = models.CharField(db_column='BPASGE_0', max_length=1, default='')
    bpadcl_0 = models.CharField(db_column='BPADCL_0', max_length=1, default='')
    cntdds_0 = models.CharField(db_column='CNTDDS_0', max_length=1, default='')
    codcra_0 = models.CharField(db_column='CODCRA_0', max_length=1, default='')
    regprh_0 = models.SmallIntegerField(db_column='REGPRH_0', default=0)
    prf_0 = models.CharField(db_column='PRF_0', max_length=1, default='')
    srv_0 = models.CharField(db_column='SRV_0', max_length=1, default='')
    cllcvt_0 = models.CharField(db_column='CLLCVT_0', max_length=1, default='')
    rskwrk_0 = models.CharField(db_column='RSKWRK_0', max_length=1, default='')
    hrmpayban_0 = models.CharField(db_column='HRMPAYBAN_0', max_length=1, default='')
    hrmtaxwag_0 = models.SmallIntegerField(db_column='HRMTAXWAG_0', default=0)
    secprh_0 = models.SmallIntegerField(db_column='SECPRH_0', default=0)
    flgapp_0 = models.SmallIntegerField(db_column='FLGAPP_0', default=0)
    flgfor_0 = models.SmallIntegerField(db_column='FLGFOR_0', default=0)
    flgpec_0 = models.SmallIntegerField(db_column='FLGPEC_0', default=0)
    chef_0 = models.CharField(db_column='CHEF_0', max_length=1, default='')
    serviceid_0 = models.CharField(db_column='SERVICEID_0', max_length=1, default='')

    create_user = models.CharField(db_column='CREUSR_0', max_length=5, default='INTER')
    create_date = models.DateTimeField(db_column='CREDAT_0', default=timezone.now)
    update_user = models.CharField(db_column='UPDUSR_0', max_length=5, default='INTER')
    update_date = models.DateTimeField(db_column='UPDDAT_0', default=timezone.now)
    create_datetime = models.DateTimeField(db_column='CREDATTIM_0', auto_now_add=True)
    update_datetime = models.DateTimeField(db_column='UPDDATTIM_0', auto_now=True)

    updtick = models.IntegerField(db_column='UPDTICK_0', default=1)
    auuid = models.BinaryField(db_column='AUUID_0')

    class Meta:
        managed = False
        db_table = 'FACILITY'
        verbose_name = 'Facility'
        verbose_name_plural = 'Facilities'
