from django.conf import settings
from django.db import models
from django.utils import timezone


class Country(models.Model):
    id = models.BigAutoField(db_column='ROWID', primary_key=True)
    country = models.CharField(db_column='CRY_0', unique=True, max_length=3, default='')
    language = models.CharField(db_column='LAN_0', max_length=3, default='')
    currency = models.CharField(db_column='CUR_0', max_length=3, default='')
    create_user = models.CharField(db_column='CREUSR_0', max_length=5, default='INTER')
    create_date = models.DateTimeField(db_column='CREDAT_0', default=timezone.now)
    update_user = models.CharField(db_column='UPDUSR_0', max_length=5, default='INTER')
    update_date = models.DateTimeField(db_column='UPDDAT_0', default=timezone.now)
    create_datetime = models.DateTimeField(db_column='CREDATTIM_0', auto_now_add=True)
    update_datetime = models.DateTimeField(db_column='UPDDATTIM_0', auto_now=True)
    auuid = models.BinaryField(db_column='AUUID_0')

    updtick_0 = models.IntegerField(db_column='UPDTICK_0', default=1)
    eeccod_0 = models.CharField(db_column='EECCOD_0', max_length=3, default='')
    cinsee_0 = models.CharField(db_column='CINSEE_0', max_length=5, default='')
    iso_0 = models.CharField(db_column='ISO_0', max_length=2, default='')
    isoa3_0 = models.CharField(db_column='ISOA3_0', max_length=3, default='')
    isonum_0 = models.CharField(db_column='ISONUM_0', max_length=3, default='')
    eecflg_0 = models.SmallIntegerField(db_column='EECFLG_0', default=0)
    eecdat_0 = models.DateTimeField(db_column='EECDAT_0', default=0)
    eecdatout_0 = models.DateTimeField(db_column='EECDATOUT_0', default=settings.DEFAULT_LEGACY_DATE)
    ctlprg_0 = models.CharField(db_column='CTLPRG_0', max_length=30, default='')
    naffmt_0 = models.CharField(db_column='NAFFMT_0', max_length=30, default='')
    telfmt_0 = models.CharField(db_column='TELFMT_0', max_length=30, default='')
    poscodfmt_0 = models.CharField(db_column='POSCODFMT_0', max_length=30, default='')
    poscodcry_0 = models.CharField(db_column='POSCODCRY_0', max_length=30, default='')
    ctycodfmt_0 = models.CharField(db_column='CTYCODFMT_0', max_length=30, default='')
    ctyupp_0 = models.SmallIntegerField(db_column='CTYUPP_0', default=0)
    ctynumfmt_0 = models.CharField(db_column='CTYNUMFMT_0', max_length=30, default='')
    adrcodfmt_0 = models.CharField(db_column='ADRCODFMT_0', max_length=30, default='')
    minzip_0 = models.SmallIntegerField(db_column='MINZIP_0', default=0)
    adrnam_0 = models.CharField(db_column='ADRNAM_0', max_length=20, default='')
    adrnam_1 = models.CharField(db_column='ADRNAM_1', max_length=20, default='')
    adrnam_2 = models.CharField(db_column='ADRNAM_2', max_length=20, default='')
    bidfmt_0 = models.CharField(db_column='BIDFMT_0', max_length=30, default='')
    pabfmt_0 = models.CharField(db_column='PABFMT_0', max_length=30, default='')
    bidcry_0 = models.CharField(db_column='BIDCRY_0', max_length=30, default='')
    crnfmt_0 = models.CharField(db_column='CRNFMT_0', max_length=30, default='')
    crtfmt_0 = models.CharField(db_column='CRTFMT_0', max_length=30, default='')
    nidfmt_0 = models.CharField(db_column='NIDFMT_0', max_length=30, default='')
    eecfmt_0 = models.CharField(db_column='EECFMT_0', max_length=30, default='')
    crnfmtflg_0 = models.SmallIntegerField(db_column='CRNFMTFLG_0', default=0)
    crtfmtflg_0 = models.SmallIntegerField(db_column='CRTFMTFLG_0', default=0)
    nidfmtflg_0 = models.SmallIntegerField(db_column='NIDFMTFLG_0', default=0)
    eecfmtflg_0 = models.SmallIntegerField(db_column='EECFMTFLG_0', default=0)
    naffmtflg_0 = models.SmallIntegerField(db_column='NAFFMTFLG_0', default=0)
    subdivfmt_0 = models.CharField(db_column='SUBDIVFMT_0', max_length=30, default='')
    cryvatnum_0 = models.CharField(db_column='CRYVATNUM_0', max_length=3, default='')
    continent_0 = models.CharField(db_column='CONTINENT_0', max_length=20, default='')
    etat_0 = models.SmallIntegerField(db_column='ETAT_0', default=0)
    etatflg_0 = models.SmallIntegerField(db_column='ETATFLG_0', default=0)
    etatflg2_0 = models.SmallIntegerField(db_column='ETATFLG2_0', default=0)
    etatfmt_0 = models.CharField(db_column='ETATFMT_0', max_length=30, default='')
    etatfmt2_0 = models.CharField(db_column='ETATFMT2_0', max_length=30, default='')
    etatctl_0 = models.SmallIntegerField(db_column='ETATCTL_0', default=0)
    socnumflg1_0 = models.SmallIntegerField(db_column='SOCNUMFLG1_0', default=0)
    poscodctl_0 = models.SmallIntegerField(db_column='POSCODCTL_0', default=0)
    bidctl_0 = models.SmallIntegerField(db_column='BIDCTL_0', default=0)
    banlng_0 = models.SmallIntegerField(db_column='BANLNG_0', default=0)
    fliban_0 = models.SmallIntegerField(db_column='FLIBAN_0', default=0)
    posobl_0 = models.SmallIntegerField(db_column='POSOBL_0', default=0)
    socnumfmt_0 = models.CharField(db_column='SOCNUMFMT_0', max_length=1, default='')
    crnobl_0 = models.SmallIntegerField(db_column='CRNOBL_0', default=0)
    crtobl_0 = models.SmallIntegerField(db_column='CRTOBL_0', default=0)
    teltcy_0 = models.CharField(db_column='TELTCY_0', max_length=10, default='')
    telreg_0 = models.CharField(db_column='TELREG_0', max_length=10, default='')
    flgsepa_0 = models.SmallIntegerField(db_column='FLGSEPA_0', default=0)
    socnumflg2_0 = models.SmallIntegerField(db_column='SOCNUMFLG2_0', default=0)
    bidcls_0 = models.CharField(db_column='BIDCLS_0', max_length=12, default='')
    socnumfmt2_0 = models.CharField(db_column='SOCNUMFMT2_0', max_length=1, default='')
    flgdue_0 = models.SmallIntegerField(db_column='FLGDUE_0', default=0)
    gspflg_0 = models.SmallIntegerField(db_column='GSPFLG_0', default=0)
    eoriflg_0 = models.SmallIntegerField(db_column='EORIFLG_0', default=0)

    class Meta:
        managed = False
        db_table = 'TABCOUNTRY'
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'
